library(shiny)
setwd("C:/Users/abhishek.b.jaiswal/Desktop/HACK17/global")
cars=read.table("carsT.txt",header=T, sep=",")
library(randomForest)
library(caret)

mod1=randomForest(class~buying+maint+doors+persons+lug_boot+safety ,data=cars)


shinyServer(
  function(input,output){
    output$Buying=renderText(input$buying)
    output$Maint=renderText(input$maint)
    output$Doors=renderText(input$doors)
    output$Persons=renderText(input$persons)
    output$Lug_boot=renderText(input$lug_boot)
    output$Safety=renderText(input$safety)
    output$Data=renderTable({head(cars)})
    output$Classplot=renderPlot({plot(cars$class)})
    output$varplot=renderPlot({varImpPlot(mod1)})
    output$predRF =renderText({
      pred_data =data.frame(buying=input$buying,maint=input$maint,doors=input$doors,persons=input$persons,lug_boot=input$lug_boot,safety=input$safety)
      #pred_data=data.frame("low","low",2,4,"med","med")
      colnames(pred_data)=c("buying", "maint","doors","persons","lug_boot","safety")
      pred_data$buying=as.factor(pred_data$buying)
      pred_data$maint=as.factor(pred_data$maint)
      pred_data$doors=as.factor(pred_data$doors)
      pred_data$persons=as.factor(pred_data$persons)
      pred_data$lug_boot=as.factor(pred_data$lug_boot)
      pred_data$safety=as.factor(pred_data$safety)
      levels(pred_data$buying)=levels(cars$buying)
      levels(pred_data$maint)=levels(cars$maint)
      levels(pred_data$lug_boot)=levels(cars$lug_boot)
      levels(pred_data$safety)=levels(cars$safety)
      levels(pred_data$doors)=c(levels(pred_data$doors),"2")
      levels(pred_data$doors)=c(levels(pred_data$doors),"3")
      levels(pred_data$doors)=c(levels(pred_data$doors),"4")
      levels(pred_data$doors)=c(levels(pred_data$doors),"5more")
      levels(pred_data$persons)=c(levels(pred_data$persons),"2")
      levels(pred_data$persons)=c(levels(pred_data$persons),"4")
      levels(pred_data$persons)=c(levels(pred_data$persons),"more")
      pred=predict(mod1,pred_data)})
  }
)